### ISSUE TITLE
dota 2 win (and maybe all games on Source 2) - crashing due to memory issue

### ISSUE THREAD

**Issue by Sirox228** [ptitSeb/box64#1049]
tried on wine 8.2 staging and wine ge 8.14. was using latest box64 from the repo, compiled with SAVE_MEM option. i set up steam and then try to run dota 2 (windows version), it loads to menu (only if i skip intro cutscene with -novid flag, otherwise it's crashing on cutscene with the same log) and then after like 5 seconds it crashes (sometimes just freezes). when look in logs the only thing that appears after i start the game is like this
```
01a8:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x3aa5c0000-0x3aa5d1000, unix_prot 0x1.
```
and it repeats like that for a VERY LOT of times, there's no even a single line with something different from that after the game started. tried to run it with BOX64_DYNAREC_STRONGMEM set to 3 and nothing changed. i can assume that it tries allocate memory, but can't for some reason and then it leads to something like SIGSEGV. i remember having the same issue in counter strike 2, so maybe it occurs in all games on Source 2.

full log
[dota2.txt](https://github.com/ptitSeb/box64/files/13260206/dota2.txt)

**Comment by ptitSeb** [comment]
This wine message happens when the memory cannot be allocated, or mhen it's allocated in another address. Is this message new with latest box64 or is it new with wine?

I need more context.

I assume you are running this on a phone with Termux. Do you have enough memory free?

The crash is not necessarily due to the memory error you see. You should add `BOX64_SHOWSEGV=1` so we have some details about any crash.

**Comment by Sirox228** [comment]
that message was always there, both wines and both boxes (new and old one). but i can difinitely say that it works a bit longer on new box.

yeah, termux, but i have enough free memory (130+ gb free and 12 gb ram)

logs after added BOX64_SHOWSEGV=1 and BOX64_LOG=2
[debug.log](https://github.com/ptitSeb/box64/files/13260388/debug.log)

**Comment by Sirox228** [comment]
i just noticed that the log when it freezes is different from the one when it crashes, so here is the one when it crashes (the one i sent before is when it freezes)
[debug.log](https://github.com/ptitSeb/box64/files/13260445/debug.log)

**Comment by ptitSeb** [comment]
The try_mmap error are normal on Android. It's an android limit (39bits of address space only), that wine doesn't know (it tries to use 47bits of address space).

There is an error, and than the stack overflows, wich is not normal. Are you using the latest box64, also with the libunwind that comes with it?

**Comment by Sirox228** [comment]
i just `make install`-ed box64 and box86, if it automatically installs libunwind, then yes. i just recompiled latest box64/box86, reinstalled steam and the game, result iz the same

**Comment by Sirox228** [comment]
it seems that log is different with latest box64
[log.txt](https://github.com/ptitSeb/box64/files/13300401/log.txt)

**Comment by ptitSeb** [comment]
Yeah, something seems blocked in a critical section. That's the latest box64 version, becasue I fixed stuffs about that yesterday.

**Comment by Sirox228** [comment]
hello, i was messing with video codecs a little bit and found out that gstreamer don't really want to work with termux for some reason, so i installed k-lite codecs pack into wine prefix and the log in dota 2 changed, now there's a clear error in wine
```
-ge-custom/bin/wine64: ../dlls/ntdll/unix/virtual.c:1571: create_view: Assertion `!((UINT_PTR)base & page_mask)' failed.
020c:err:seh:call_stack_handlers invalid frame 000000008BFFF3B8 (000000008BE02000-000000008BF00000)
020c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
```
this was tested on wine ge 13, i don't think that there would really be issues in wine with running dota, also ge is based on proton, so it should run valve games without issues.
here's the full log: 
[log.txt](https://github.com/ptitSeb/box64/files/13606392/log.txt)
i know, that in that log box64 version is a bit old, thats because on latest version, from what i see, stack overflow error is again there
```
0244:err:virtual:virtual_setup_exception stack overflow 1648 bytes addr 0x170034110 stack 0x991e0990 (0x991e0000-0x991e1000-0x992e0000)
```
here's the full log with latest version and stack overflow:
[log.txt](https://github.com/ptitSeb/box64/files/13606419/log.txt)

**Comment by ptitSeb** [comment]
Mmmm, can you bisect the moment that virtual_setup_exception stack came back? We need to be able to use latest box64 version at all time.

**Comment by Sirox228** [comment]
stack overflow still happens on commit `8901d1c` and is not happening on commit `dfd2a4e`, but i need to say that there's no wine error in logs on `dfd2a4e` commit, but this window appears when the game dies 
![Screenshot_2023-12-08-18-21-32-286_com termux x11](https://github.com/ptitSeb/box64/assets/71220271/b8f5d321-f724-469f-990d-75db8e78129c)

**Comment by Sirox228** [comment]
i tried to run it with `BOX64_DYNAREC=0`, there's no stack overflow, but the game crashes, so it seems that stack overflow happens in dynarec, but the main problem is not in it, also i think i found out why there are no wine errors in logs, it seems that winedbg died

**Comment by Sirox228** [comment]
it seems that stack overfoow happens only on latest wine ge (8.25), when i tried to use 8.13 i got the same error as on old box64

**Comment by Sirox228** [comment]
the error seems to be the same for counter strike 2
```
-ge-custom/bin/wine64: ../dlls/ntdll/unix/virtual.c:1571: create_view: Assertion `!((UINT_PTR)base & page_mask)' failed.
03c8:err:virtual:virtual_setup_exception stack overflow 464 bytes addr 0x1700595c2 stack 0xb0e30 (0xb0000-0xb1000-0x1b0000)
```
so i guess that happens because of source 2 engine

**Comment by Sirox228** [comment]
just updated to wine ge 8.25 and it seems that there's stack overflow
log:
[log.txt](https://github.com/ptitSeb/box64/files/13942897/log.txt)

**Comment by Sirox228** [comment]
wine issue
