### ISSUE TITLE
SOMA, v1.61 (50361), Linux x64, GOG, Segmentation fault

### ISSUE THREAD

**Issue by ricoazzurro** [ptitSeb/box64#545]
### Description

SOMA, v1.61 (50361), Linux x64, GOG, Engine: HPL
Rock 5B, Box64 with Dynarec v0.2.3 38a5e55, PAN_MESA_DEBUG=gofaster,gl3

Not working, ending with Segmentation fault. 
Also reported here, https://github.com/ptitSeb/box86-compatibility-list/issues/245

Already tested:
- `-force-opengl`, no effect.

```bash
rico [ /opt/games/soma ]$ ./Soma.bin.x86_64 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 Cores
Params database has 21 entries
Using bash "/home/rico/box64/tests/bash"
Box64 with Dynarec v0.2.1 c5e085b built on Mar 10 2023 13:29:51
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 57 Env var
Looking for ./Soma.bin.x86_64
Rename process to "Soma.bin.x86_64"
Using native(wrapped) libGL.so.1
Using native(wrapped) libGLU.so.1
Using emulated /opt/games/soma/lib64/libtheora.so.0
Using native(wrapped) libvorbis.so.0
Using native(wrapped) libvorbisfile.so.3
Using native(wrapped) libogg.so.0
Using emulated /opt/games/soma/lib64/libIL.so.1
Using native(wrapped) libz.so.1
Using emulated /opt/games/soma/lib64/libfmodex64-4.44.62.so
Using emulated /opt/games/soma/lib64/libfmodevent64-4.44.62.so
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Look for pthread_yield in loaded elfs
Found symbol with version GLIBC_2.17, value = 0x7fa64f1520
1484|SIGSEGV @0x7fa6448f54 (pthread_setschedparam (/usr/lib/libc.so.6)) (x64pc=0xa0613/???:"???", rsp=0x101fff148, stack=0x101800000:0x102000000 own=(nil) fp=(nil)), for accessing 0xd0 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x00000000012746bf RSP-0x18:0x000000007079f090 RSP-0x10:0x0000000000e95259 RSP-0x08:0x0000000072c2b1e8
RSP+0x00:0x000000000127474d RSP+0x08:0x0000000000000000 RSP+0x10:0x00000000705b2c10 RSP+0x18:0x000000007427d780
RAX:0x000000007079f0e0 RCX:0x00000000366cadf0 RDX:0x000000007079f090 RBX:0x000000007079f090 
RSP:0x0000000101fff148 RBP:0x0000000000000000 RSI:0x0000000072c2b1e8 RDI:0x0000000001279e20 
 R8:0x0000000001f55640  R9:0x0000000000000000 R10:0x00000000019ce935 R11:0x0000000070786af0 
R12:0x00000000705bd820 R13:0x00000000705d18b0 R14:0x0000000000000001 R15:0x0000000101fff180 
Segmentation fault (core dumped)
```

### Tested on

RADXA Rock 5B (rk3588) 16GB
LFS, BSP kernel 5.10.110+ rkr3.6, Gnome 43.4, Box64 with Dynarec v0.2.3 38a5e55
1080p, default game setting

### Reproduce

```bash
cd $game_folder
export PAN_MESA_DEBUG=gofaster,gl3
./Soma.bin.x86_64
```
### Logs
Pasted above

### Status
**Previous behavior:** 

None reported

**Current behavior:**

Segmentation fault via box64 

### OpenGL

OpenGL 3.3
HPL Engine 3

### Additional Information

`PAN_MESA_DEBUG=gofaster,gl3`
Box64 with Dynarec v0.2.3 38a5e55, compiled with `-DRK3588=1`

https://www.pcgamingwiki.com/wiki/SOMA

**Comment by ptitSeb** [comment]
Soma works fine for me. No issue loading (on arm mini pc using a Radeon Rx550)
It does need `BOX64_DYNAREC_FASTROUND=0`

I think it's a mesa issue you ahev on your side, the game use a lot of extensions.

**Comment by ricoazzurro** [comment]
Thanks for adding rc for the game,
with BOX64_DYNAREC_FASTROUND=0, no luck.
will wait for mesa for this board to mature.

```bash
rico [ /opt/games/soma ]$ ./Soma.bin.x86_64 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 Cores
Params database has 22 entries
Using bash "/home/rico/box64/tests/bash"
Box64 with Dynarec v0.2.3 38a5e55 built on Mar 11 2023 19:31:36
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 57 Env var
Looking for ./Soma.bin.x86_64
Apply RC params for Soma.bin.x86_64
Applying BOX64_DYNAREC_FASTROUND=0
Rename process to "Soma.bin.x86_64"
Using native(wrapped) libGL.so.1
Using native(wrapped) libGLU.so.1
Using emulated /opt/games/soma/lib64/libtheora.so.0
Using native(wrapped) libvorbis.so.0
Using native(wrapped) libvorbisfile.so.3
Using native(wrapped) libogg.so.0
Using emulated /opt/games/soma/lib64/libIL.so.1
Using native(wrapped) libz.so.1
Using emulated /opt/games/soma/lib64/libfmodex64-4.44.62.so
Using emulated /opt/games/soma/lib64/libfmodevent64-4.44.62.so
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Look for pthread_yield in loaded elfs
Found symbol with version GLIBC_2.17, value = 0x7fa7211520
3278|SIGSEGV @0x7fa7168f54 (pthread_setschedparam (/usr/lib/libc.so.6)) (x64pc=0xa0613/???:"???", rsp=0x101fff138, stack=0x101800000:0x102000000 own=(nil) fp=(nil)), for accessing 0xd0 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x00000000012746bf RSP-0x18:0x000000005aed9330 RSP-0x10:0x0000000000e95259 RSP-0x08:0x000000005d34fea8
RSP+0x00:0x000000000127474d RSP+0x08:0x0000000000000000 RSP+0x10:0x000000005acebff0 RSP+0x18:0x000000005e9b86f0
RAX:0x000000005aed9380 RCX:0x00000000366cadf0 RDX:0x000000005aed9330 RBX:0x000000005aed9330 
RSP:0x0000000101fff138 RBP:0x0000000000000000 RSI:0x000000005d34fea8 RDI:0x0000000001279e20 
 R8:0x0000000001f55640  R9:0x0000000000000000 R10:0x00000000019ce935 R11:0x000000005aec0d80 
R12:0x000000005acf5830 R13:0x000000005ad02f20 R14:0x0000000000000001 R15:0x0000000101fff170 
Segmentation fault (core dumped)
```

**Comment by ptitSeb** [comment]
try with software mesa, just to be sure (it will be super slow, has this game has great graphics)

**Comment by ricoazzurro** [comment]
how to force software mesa ? google gives me `LIBGL_ALWAYS_SOFTWARE=1`
no luck.

my driver info

```bash
rico [ /opt/games/soma ]$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Panfrost (0xffffffff)
    Device: Mali-G610 (Panfrost) (0xffffffff)
    Version: 23.0.0
    Accelerated: yes
    Video memory: 15721MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Panfrost
OpenGL renderer string: Mali-G610 (Panfrost)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 23.0.0-devel (git-120202c675)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.3 (Compatibility Profile) Mesa 23.0.0-devel (git-120202c675)
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.0.0-devel (git-120202c675)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

force llvmpipe

```bash
rico [ /opt/games/soma ]$ LIBGL_ALWAYS_SOFTWARE=1 glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 15.0.7, 128 bits) (0xffffffff)
    Version: 23.0.0
    Accelerated: no
    Video memory: 15721MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 15.0.7, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 23.0.0-devel (git-120202c675)
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 23.0.0-devel (git-120202c675)
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.0-devel (git-120202c675)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

run the game force software
```bash
rico [ /opt/games/soma ]$ LIBGL_ALWAYS_SOFTWARE=1 BOX64_DYNAREC_FASTROUND=0 box64 ./"Soma.bin.x86_64"
Dynarec will try tp generate x86 precise IEEE->int rounding
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 Cores
Params database has 22 entries
Using bash "/home/rico/box64/tests/bash"
Box64 with Dynarec v0.2.3 38a5e55 built on Mar 11 2023 19:31:36
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 58 Env var
Looking for ./Soma.bin.x86_64
Apply RC params for Soma.bin.x86_64
Applying BOX64_DYNAREC_FASTROUND=0
Rename process to "Soma.bin.x86_64"
Using native(wrapped) libGL.so.1
Using native(wrapped) libGLU.so.1
Using emulated /opt/games/soma/lib64/libtheora.so.0
Using native(wrapped) libvorbis.so.0
Using native(wrapped) libvorbisfile.so.3
Using native(wrapped) libogg.so.0
Using emulated /opt/games/soma/lib64/libIL.so.1
Using native(wrapped) libz.so.1
Using emulated /opt/games/soma/lib64/libfmodex64-4.44.62.so
Using emulated /opt/games/soma/lib64/libfmodevent64-4.44.62.so
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Look for pthread_yield in loaded elfs
Found symbol with version GLIBC_2.17, value = 0x7f8d9f1520
5254|SIGSEGV @0x7f8d948f54 (pthread_setschedparam (/usr/lib/libc.so.6)) (x64pc=0xa0613/???:"???", rsp=0x101fff108, stack=0x101800000:0x102000000 own=(nil) fp=(nil)), for accessing 0xd0 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x00000000012746bf RSP-0x18:0x000000005b094bd0 RSP-0x10:0x0000000000e95259 RSP-0x08:0x000000005c81b028
RSP+0x00:0x000000000127474d RSP+0x08:0x0000000000000000 RSP+0x10:0x000000005aeb2250 RSP+0x18:0x000000005eb72890
RAX:0x000000005b094c20 RCX:0x00000000366cadf0 RDX:0x000000005b094bd0 RBX:0x000000005b094bd0 
RSP:0x0000000101fff108 RBP:0x0000000000000000 RSI:0x000000005c81b028 RDI:0x0000000001279e20 
 R8:0x0000000001f55640  R9:0x0000000000000000 R10:0x00000000019ce935 R11:0x000000005b07c630 
R12:0x000000005aebef50 R13:0x000000005aeb4d60 R14:0x0000000000000001 R15:0x0000000101fff140 
Segmentation fault (core dumped)
```

**Comment by ricoazzurro** [comment]
- In the game's readme file,

> Game prerequisites:
> 
> OpenGL 3.2 as well as the following extensions:
>  * EXT_texture_compression_s3tc
>  * EXT_texture_filter_anisotropic
>  * ARB_explicit_attrib_location

- Now I moved to use panfrost/panthor as my gpu driver, and tested various envs and software render, the game is still not working - -
Box64 with Dynarec v0.2.7 856d265
Rock 5B, LFS, Kernel rk-6.1-rkr1-panthor-v6, Mesa 24.1.0, Gnome 46

```bash
rico [ ~ ]$ cat /opt/games/soma/box64-start.sh 
#!/bin/bash

cd /opt/games/soma

# export PAN_MESA_DEBUG=gl3
# export LC_ALL=C
# export LD_LIBRARY_PATH=/opt/box-libs/aarch64/:/opt/box-libs/x86_64/:./x64/
export BOX64_DYNAREC_FASTROUND=0
# export BOX64_DYNAREC_STRONGMEM=2
# export BOX64_PREFER_EMULATED=1
# export BOX64_PREFER_WRAPPED=1
# export BOX64_DYNAREC_SAFEFLAGS=2
# export BOX64_DYNAREC_BIGBLOCK=0
# export BOX64_DYNAREC_CALLRET=0

LIBGL_ALWAYS_SOFTWARE=1 box64 ./"Soma.bin.x86_64"
```

- With `PAN_MESA_DEBUG=gl3` and `BOX64_DYNAREC_FASTROUND=0`, after several crashes and re-trial, I managed to pass the loading screen and title screen, and tried to set all in-game video options to lowest, then the game just crashed and move further.

![soma-title-screen](https://github.com/ptitSeb/box64/assets/108268247/b177e135-6409-4efa-be25-87dd116d9bb8)

- With `LIBGL_ALWAYS_SOFTWARE=1` and `BOX64_DYNAREC_FASTROUND=0`, I can only see the loading screen then freeze at 100%, can not even see the title screen.

**Comment by ptitSeb** [comment]
I have played this games on  Arm64 machines with Radeon grapic card (mesa), NVidia graphic card (prop. driver) and Adreno (mesa). The game works fine, but need a beefy graphic card and opengl driver.

**Comment by ricoazzurro** [comment]
My poor board and immature gpu driver! 

Thanks for testing in various boards and set-ups.

**Comment by ksco** [comment]
Hi @ricoazzurro, I pushed a fix 2ee846f48e7fa9b103f0949f63f91712ca7b03ca which might solve you issue, can you try again on this?

**Comment by LukeShortCloud** [comment]
Soma is also working for me (X Elite).

**Comment by LukeShortCloud** [comment]
@ricoazzurro If you can provide the log output of `BOX64_ROLLING_LOG=1 box64 ./Soma.x86_64`, then we can re-open this issue. No one else on our team is able to replicate the issue.

**Comment by ricoazzurro** [comment]
@ksco Sorry buddy, I totally forgot this game. My bad.

@LukeShortCloud Thanks for the ping, here's the log:

One more thing,
I'm using `SDL3`, then `sdl2-compat`, then `sdl12-compat`.
Not sure if it's the issue. As once Seb said that sdl12-compat was not the same as pure sdl1.

Or it's my gpu, only semi working vulkan. (not able to run dxvk, but good enough for warzone2100)


1. `BOX64_ROLLING_LOG=1 box64 ./Soma.x86_64`
Only saw a gl error window.

```bash
rico [ /opt/games/soma ]$ BOX64_ROLLING_LOG=1 box64 ./"Soma.bin.x86_64"
[BOX64] Box64 arm64 v0.3.7 4a8a373 with Dynarec built on Jul 23 2025 04:21:52
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2
[BOX64] Running on Cortex-A55 with 8 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 24.0 MHz emulating 3.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 66 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/opt/rustc/bin/:/usr/local/bin/:/usr/bin/:/opt/ant/bin/:/opt/jdk/bin/:/opt/bin/
[BOX64] Looking for ./Soma.bin.x86_64
[BOX64] BOX64ENV: Variables overridden:
	BOX64_DYNAREC_FASTROUND=0
	BOX64_ROLLING_LOG=1
[BOX64] Rename process to "Soma.bin.x86_64"
[BOX64] Using native(wrapped) libGL.so.1
[BOX64] Using native(wrapped) libGLU.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libtheora.so.0
[BOX64] Using native(wrapped) libvorbis.so.0
[BOX64] Using native(wrapped) libvorbisfile.so.3
[BOX64] Using native(wrapped) libogg.so.0
[BOX64] Using emulated /opt/games/soma/lib64/libIL.so.1
[BOX64] Using native(wrapped) libz.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libfmodex64-4.44.62.so
[BOX64] Using emulated /opt/games/soma/lib64/libfmodevent64-4.44.62.so
[BOX64] Using native(wrapped) libSDL2-2.0.so.0
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) libbsd.so.0
Fontconfig warning: using without calling FcInit()
INFO: Leaked thread (0x5d7fa330)
INFO: Leaked thread (0x5d7fcf30)
INFO: Leaked thread (0x5d7f5070)
INFO: Leaked thread (0x5d7f45d0)
INFO: Leaked thread (0x5d7ccd70)
INFO: Leaked thread (0x5d800330)
INFO: Leaked thread (0x5d7ebc10)
INFO: Leaked thread (0x60fee5f0)
INFO: Leaked thread (0x60f97a00)
INFO: Leaked thread (0x60c96500)
```

<img width="1488" height="1170" alt="Image" src="https://github.com/user-attachments/assets/7eb11f9f-1830-40d3-bd64-80fbc15ef01e" />

2. `BOX64_DYNAREC=0 BOX64_ROLLING_LOG=1 LIBGL_ALWAYS_SOFTWARE=1 box64 ./"Soma.bin.x86_64"`
```bash
rico [ /opt/games/soma ]$ BOX64_DYNAREC=0 BOX64_ROLLING_LOG=1 LIBGL_ALWAYS_SOFTWARE=1 box64 ./"Soma.bin.x86_64"
[BOX64] Box64 arm64 v0.3.7 4a8a373 with Dynarec built on Jul 23 2025 04:21:52
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2
[BOX64] Running on Cortex-A55 with 8 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 24.0 MHz emulating 3.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 68 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/opt/rustc/bin/:/usr/local/bin/:/usr/bin/:/opt/ant/bin/:/opt/jdk/bin/:/opt/bin/
[BOX64] Looking for ./Soma.bin.x86_64
[BOX64] BOX64ENV: Variables overridden:
	BOX64_DYNAREC_FASTROUND=0
	BOX64_ROLLING_LOG=1
	BOX64_DYNAREC=0
[BOX64] Rename process to "Soma.bin.x86_64"
[BOX64] Using native(wrapped) libGL.so.1
[BOX64] Using native(wrapped) libGLU.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libtheora.so.0
[BOX64] Using native(wrapped) libvorbis.so.0
[BOX64] Using native(wrapped) libvorbisfile.so.3
[BOX64] Using native(wrapped) libogg.so.0
[BOX64] Using emulated /opt/games/soma/lib64/libIL.so.1
[BOX64] Using native(wrapped) libz.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libfmodex64-4.44.62.so
[BOX64] Using emulated /opt/games/soma/lib64/libfmodevent64-4.44.62.so
[BOX64] Using native(wrapped) libSDL2-2.0.so.0
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Last calls
[BOX64] 6688|0x7fff040b071c: Calling malloc(0x10, 0x19CEFFB, 0x6, ...) => return 0x675237C0
[BOX64] 6688|0x127430d: Calling SDL_CreateMutex(0x675237C0, 0x19CEFFB, 0x6, ...) => return 0x667862F0
[BOX64] 6688|0x7fff040b071c: Calling malloc(0x20, 0x19CEFFB, 0x6, ...) => return 0x66786330
[BOX64] 6688|0x12743c2: Calling SDL_CreateSemaphore(0x0, 0x19CEFFB, 0x6, ...) => return 0x66786360
[BOX64] 6688|0x12743cb: Calling SDL_CreateMutex(0x0, 0x19CEFFB, 0x6, ...) => return 0x66786390
[BOX64] 6688|0xe952f9: Calling SDL_AtomicSet(0x66786348, 0x0, 0x6, ...) => return 0x0
[BOX64] 6688|0x7fff040f5fa5: Calling strlen("TextureStream") => return 0xD
[BOX64] 6688|0x7fff040b071c: Calling malloc(0x26, 0x0, 0xFFFFA17FEE78, ...) => return 0x667863D0
[BOX64] 6688|0x7fff040f5b24: Calling memcpy(0x667863E8, 0x19CF002, 0xD, ...) => return 0x667863E8
[BOX64] 6688|0x7fff040b071c: Calling malloc(0x40, 0x1, 0xFFFFA17FEE80, ...) => return 0x66786400
[BOX64] 6688|0x12746bf: Calling SDL_CreateThread(0x1279E20, 0x667863E8, 0x66786400, ...) => return 0x69C0B6E0
[BOX64] 6688|PltResolver "SDL_GetThreadID" => return 0x0
[BOX64] 6688|0x127473f: Calling SDL_GetThreadID(0x69C0B6E0, 0x0, 0x66786400, ...) => return 0x0
[BOX64] 6688|PltResolver "pthread_setschedparam" => return 0x0
[BOX64] 6688|0x127474d: Calling pthread_setschedparam(0x0, 0x0, 0xFFFFA17FEE50, ...) => return 
[BOX64] 6688|0x7fff040f5b24: Calling memcpy(0x66786228, 0x19CEFFB, 0x6, ...) => return 0x66786228
[BOX64] 6688|SIGSEGV @0xffffa20fcf8c (pthread_setschedparam(/usr/lib/libc.so.6)) (x64pc=0x300b05d3/"???", rsp=0xffffa17fee48, stack=0xffffa1000000:0xffffa1800000 own=(nil) fp=(nil)), for accessing 0xd0 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x00000000012746bf RSP-0x18:0x0000000066786400 RSP-0x10:0x000000006657ff20 RSP-0x08:0x00000000000002a1
RSP+0x00:0x000000000127474d RSP+0x08:0x0000000000000000 RSP+0x10:0x0000ffff948cb010 RSP+0x18:0x0000ffff948cb0f0
RAX:0x0000000000000000 RCX:0x0000000000000001 RDX:0x0000ffffa17fee50 RBX:0x0000000066786400 
RSP:0x0000ffffa17fee48 RBP:0x0000000000000000 RSI:0x0000000000000000 RDI:0x0000000000000000 
 R8:0x0000000000000001  R9:0x0000000000000000 R10:0x00000000019ce935 R11:0x000000006675eef0 
R12:0x000000006676ce90 R13:0x0000000066752b00 R14:0x0000ffff948cb0b0 R15:0x0000ffff948cb078 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 
Segmentation fault         (core dumped) BOX64_DYNAREC=0 BOX64_ROLLING_LOG=1 LIBGL_ALWAYS_SOFTWARE=1 box64 ./"Soma.bin.x86_64"
```

3. `BOX64_DYNAREC=0 BOX64_ROLLING_LOG=1 MESA_GL_VERSION_OVERRIDE="3.3" MESA_GLSL_VERSION_OVERRIDE="330" box64 ./"Soma.bin.x86_64"
`
```bash
rico [ /opt/games/soma ]$ BOX64_DYNAREC=0 BOX64_ROLLING_LOG=1 MESA_GL_VERSION_OVERRIDE="3.3" MESA_GLSL_VERSION_OVERRIDE="330" box64 ./"Soma.bin.x86_64"
[BOX64] Box64 arm64 v0.3.7 4a8a373 with Dynarec built on Jul 23 2025 04:21:52
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2
[BOX64] Running on Cortex-A55 with 8 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 24.0 MHz emulating 3.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 69 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/opt/rustc/bin/:/usr/local/bin/:/usr/bin/:/opt/ant/bin/:/opt/jdk/bin/:/opt/bin/
[BOX64] Looking for ./Soma.bin.x86_64
[BOX64] BOX64ENV: Variables overridden:
	BOX64_DYNAREC_FASTROUND=0
	BOX64_ROLLING_LOG=1
	BOX64_DYNAREC=0
[BOX64] Rename process to "Soma.bin.x86_64"
[BOX64] Using native(wrapped) libGL.so.1
[BOX64] Using native(wrapped) libGLU.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libtheora.so.0
[BOX64] Using native(wrapped) libvorbis.so.0
[BOX64] Using native(wrapped) libvorbisfile.so.3
[BOX64] Using native(wrapped) libogg.so.0
[BOX64] Using emulated /opt/games/soma/lib64/libIL.so.1
[BOX64] Using native(wrapped) libz.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libfmodex64-4.44.62.so
[BOX64] Using emulated /opt/games/soma/lib64/libfmodevent64-4.44.62.so
[BOX64] Using native(wrapped) libSDL2-2.0.so.0
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Last calls
[BOX64] 6849|0x7fff040b071c: Calling malloc(0x10, 0x19CEFFB, 0x6, ...) => return 0x7611CBD0
[BOX64] 6849|0x127430d: Calling SDL_CreateMutex(0x7611CBD0, 0x19CEFFB, 0x6, ...) => return 0x735B6220
[BOX64] 6849|0x7fff040b071c: Calling malloc(0x20, 0x19CEFFB, 0x6, ...) => return 0x735B6260
[BOX64] 6849|0x12743c2: Calling SDL_CreateSemaphore(0x0, 0x19CEFFB, 0x6, ...) => return 0x735B6290
[BOX64] 6849|0x12743cb: Calling SDL_CreateMutex(0x0, 0x19CEFFB, 0x6, ...) => return 0x735B62C0
[BOX64] 6849|0xe952f9: Calling SDL_AtomicSet(0x735B6278, 0x0, 0x6, ...) => return 0x0
[BOX64] 6849|0x7fff040f5fa5: Calling strlen("TextureStream") => return 0xD
[BOX64] 6849|0x7fff040b071c: Calling malloc(0x26, 0x0, 0xFFFF935FEE48, ...) => return 0x735B6300
[BOX64] 6849|0x7fff040f5b24: Calling memcpy(0x735B6318, 0x19CF002, 0xD, ...) => return 0x735B6318
[BOX64] 6849|0x7fff040b071c: Calling malloc(0x40, 0x1, 0xFFFF935FEE50, ...) => return 0x735B6330
[BOX64] 6849|0x12746bf: Calling SDL_CreateThread(0x1279E20, 0x735B6318, 0x735B6330, ...) => return 0x76A3B560
[BOX64] 6849|PltResolver "SDL_GetThreadID" => return 0x0
[BOX64] 6849|0x127473f: Calling SDL_GetThreadID(0x76A3B560, 0x0, 0x735B6330, ...) => return 0x0
[BOX64] 6849|PltResolver "pthread_setschedparam" => return 0x0
[BOX64] 6849|0x127474d: Calling pthread_setschedparam(0x0, 0x0, 0xFFFF935FEE20, ...) => return 
[BOX64] 6849|0x7fff040f5b24: Calling memcpy(0x735B6158, 0x19CEFFB, 0x6, ...) => return 0x735B6158
[BOX64] 6849|SIGSEGV @0xffff93ffcf8c (pthread_setschedparam(/usr/lib/libc.so.6)) (x64pc=0x300b05d3/"???", rsp=0xffff935fee18, stack=0xffff92e00000:0xffff93600000 own=(nil) fp=(nil)), for accessing 0xd0 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x00000000012746bf RSP-0x18:0x00000000735b6330 RSP-0x10:0x00000000733adf70 RSP-0x08:0x00000000000002a1
RSP+0x00:0x000000000127474d RSP+0x08:0x0000000000000000 RSP+0x10:0x0000ffff872eb010 RSP+0x18:0x0000ffff872eb0f0
RAX:0x0000000000000000 RCX:0x0000000000000001 RDX:0x0000ffff935fee20 RBX:0x00000000735b6330 
RSP:0x0000ffff935fee18 RBP:0x0000000000000000 RSI:0x0000000000000000 RDI:0x0000000000000000 
 R8:0x0000000000000001  R9:0x0000000000000000 R10:0x00000000019ce935 R11:0x00000000735a0ba0 
R12:0x00000000735a8ff0 R13:0x00000000735967d0 R14:0x0000ffff872eb0b0 R15:0x0000ffff872eb078 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 
Segmentation fault         (core dumped) BOX64_DYNAREC=0 BOX64_ROLLING_LOG=1 MESA_GL_VERSION_OVERRIDE="3.3" MESA_GLSL_VERSION_OVERRIDE="330" box64 ./"Soma.bin.x86_64"
```

**Comment by ricoazzurro** [comment]
However, since both of you plus Seb got it working.
I suggest that let this issue remain closed.

Since it's too much for my board anyway and it's just one game :)

**Comment by ptitSeb** [comment]
@ricoazzurro according to the trace, I see `SDL_GetThreadID(XXX)` returning "0", wich is not normal at all. The subsequent call to `pthread_setschedparam(...)` with `0x0`as ThreadID then crash... I would say it's normal. The issue is `SDL_GetThreadID(..)` here that is returning NULL. It's used with the return value of `SDL_CreateThread(...)` as paramter, so this sequence is completly normal!
I would say the issue is in sdl2-compat probably yes. I don't see box64 being at fault here.
If you have a copy of the x64 version of sdl2 (maybe in the game folder), you might run it with emulated sdl2, that might just works.

**Comment by ricoazzurro** [comment]
Working now with `BOX64_PREFER_EMULATED=1`.

Yahooooooooo~

Q. How to set emulating game's `/opt/games/soma/lib64/libSDL2-2.0.so.0` without emulating all those libs coming with the game?
`export LD_LIBRARY_PATH=./lib64/libSDL2-2.0.so.0` not working. Box64 will still prefer wrapping libSDL2-2.0.so .

Log,

```bash
rico [ /opt/games/soma ]$ ./box64-start.sh 
[BOX64] Box64 arm64 v0.3.7 4a8a373 with Dynarec built on Jul 23 2025 04:21:52
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2
[BOX64] Running on Cortex-A55 with 8 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 24.0 MHz emulating 3.0 GHz
[BOX64] Detected 48bits at least of address space
[BOX64] Counted 69 Env var
[BOX64] Library search path: 
[BOX64] Binary search path: ./:bin/:/opt/rustc/bin/:/usr/local/bin/:/usr/bin/:/opt/ant/bin/:/opt/jdk/bin/:/opt/bin/
[BOX64] Looking for ./Soma.bin.x86_64
[BOX64] BOX64ENV: Variables overridden:
	BOX64_DYNAREC_FASTROUND=0
	BOX64_PREFER_EMULATED=1
[BOX64] Rename process to "Soma.bin.x86_64"
[BOX64] Using native(wrapped) libGL.so.1
[BOX64] Using native(wrapped) libGLU.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libtheora.so.0
[BOX64] Using emulated /opt/games/soma/lib64/libvorbis.so.0
[BOX64] Using emulated /opt/games/soma/lib64/libvorbisfile.so.3
[BOX64] Using emulated /opt/games/soma/lib64/libogg.so.0
[BOX64] Using emulated /opt/games/soma/lib64/libIL.so.1
[BOX64] Using native(wrapped) libz.so.1
[BOX64] Using emulated /opt/games/soma/lib64/libfmodex64-4.44.62.so
[BOX64] Using emulated /opt/games/soma/lib64/libfmodevent64-4.44.62.so
[BOX64] Using emulated /opt/games/soma/lib64/libSDL2-2.0.so.0
[BOX64] Using native(wrapped) libpthread.so.0
[BOX64] Using native(wrapped) libdl.so.2
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
[BOX64] Using native(wrapped) libm.so.6
[BOX64] Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
[BOX64] Using native(wrapped) libc.so.6
[BOX64] Using native(wrapped) ld-linux-x86-64.so.2
[BOX64] Using native(wrapped) libutil.so.1
[BOX64] Using native(wrapped) librt.so.1
[BOX64] Using native(wrapped) libbsd.so.0
[BOX64] Using native(wrapped) libudev.so.1
[BOX64] Using native(wrapped) libX11.so.6
[BOX64] Using native(wrapped) libxcb.so.1
[BOX64] Using native(wrapped) libXau.so.6
[BOX64] Using native(wrapped) libXdmcp.so.6
[BOX64] Using native(wrapped) libXext.so.6
[BOX64] Using native(wrapped) libXcursor.so.1
[BOX64] Using native(wrapped) libXfixes.so.3
[BOX64] Using native(wrapped) libXrender.so.1
[BOX64] Using native(wrapped) libXinerama.so.1
[BOX64] Using native(wrapped) libXi.so.6
[BOX64] Using native(wrapped) libXrandr.so.2
[BOX64] Using native(wrapped) libXss.so.1
[BOX64] Using native(wrapped) libXxf86vm.so.1
[BOX64] Using native(wrapped) libdbus-1.so.3
[BOX64] Using native(wrapped) libasound.so.2
[BOX64] Using native(wrapped) libpulse-simple.so.0
[BOX64] Using native(wrapped) libpulse.so.0
[BOX64] Sigfault/Segbus while quitting, exiting silently
```

<img width="2164" height="1398" alt="Image" src="https://github.com/user-attachments/assets/398e3f03-7ac7-4f7c-be93-2df62d46de69" />

**Comment by ptitSeb** [comment]
Use `BOX64_EMULATED_LIBS=libSDL2-2.0.so.0`
